# Gruber Darker Kitty theme.

foreground #e4e4ef
background #181818
selection_foreground #e4e4ef
selection_background #453d41

cursor #f4f4ff
cursor_text_color #181818

url_color #96a6c8

active_border_color #96a6c8
inactive_border_color #484848
bell_border_color #ffdd33

active_tab_foreground #e4e4ef
active_tab_background #453d41
inactive_tab_foreground #8c8c8c
inactive_tab_background #181818
tab_bar_background #181818

color0 #181818
color8 #484848

color1 #f43841
color9 #ff4f58

color2 #73c936
color10 #73c936

color3 #ffdd33
color11 #ffdd33

color4 #96a6c8
color12 #96a6c8

color5 #9e95c7
color13 #9e95c7

color6 #95a99f
color14 #95a99f

color7 #e4e4ef
color15 #f4f4ff

window_padding_width 8
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template " {index}: {title} "
active_tab_font_style bold
inactive_tab_font_style normal
